#!/bin/bash
HELPERS="vigilant_waddle_e2e_api_db vigilant_waddle_e2e_api_client"
CLIENT_CONTAINER="vigilant_waddle_e2e_api_client"
MAIN_CONTAINER="vigilant_waddle_e2e_api_test_runner"
HOSTNAME=$(hostname)
WANT_HOST=nave-jean

if [ ! -e ".dockerignore" ]; then
	echo ".docker/dbdata" >> .dockerignore
fi

if [ ! -e ".env.test.local" ]; then
	cp .env.test.example .env.test.local
fi

if [ ! -e ".docker/dockerize/dockerize" ]; then
	./local-scripts/local-dockerize-download
fi

for CONTAINER in $HELPERS; do
	if [[ "${HOSTNAME}" == "${WANT_HOST}" ]]; then
		docker-compose -f docker-compose.e2e.yml up -d $CONTAINER
	else
		docker-compose -f docker-compose.e2e.yml up -d --build --force-recreate $CONTAINER
	fi
done

if [[ "${HOSTNAME}" == "${WANT_HOST}" ]]; then
	docker-compose -f docker-compose.e2e.yml up "${MAIN_CONTAINER}"
else
	docker-compose -f docker-compose.e2e.yml up --build --force-recreate "${MAIN_CONTAINER}"
fi

EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' "${MAIN_CONTAINER}")

if [[ "${HOSTNAME}" == "${WANT_HOST}" ]]; then
	docker-compose -f docker-compose.e2e.yml logs "${CLIENT_CONTAINER}"
fi

docker-compose -f docker-compose.e2e.yml down

if [ -e ".dockerignore" ]; then
	rm .dockerignore
fi

exit $EXIT_CODE
