#!/bin/bash

# tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

if [ ! -e ".docker/dockerize" ]; then
	DOCKERIZE_VERSION=v0.6.1
	wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
	mkdir -p .docker/dockerize
	tar -C .docker/dockerize -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
	rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
fi


