definitions:
  adapter.AuthCredentials:
    properties:
      email:
        example: john@doe.com
        type: string
      password:
        example: "123456"
        maxLength: 64
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  adapter.RegisterProducer:
    properties:
      email:
        example: john@doe.com
        type: string
      password:
        example: "123456"
        maxLength: 64
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  adapter.RegisterStudent:
    properties:
      email:
        example: john@doe.com
        type: string
      password:
        example: "123456"
        maxLength: 64
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  handler.HttpAcceptedLogout:
    properties:
      message:
        example: logged out
        type: string
    type: object
  handler.HttpAccessToken:
    properties:
      access_token:
        example: OGE4MTlhMTctYTMxZS00OTE0LWE4ZjAtMzQ1Njg5ZThiMzg1OjJmZjhiOGIzLTU0OWItNGRjMi04Mjc4LWVhMDdlNjQxMGY1ZA==
        type: string
    type: object
  handler.HttpNewProducer:
    properties:
      data:
        $ref: '#/definitions/handler.HttpProducer'
    type: object
  handler.HttpNewStudent:
    properties:
      data:
        $ref: '#/definitions/handler.HttpStudent'
    type: object
  handler.HttpProducer:
    properties:
      email:
        example: john@doe.com
        format: email
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      scopes:
        example: producer
        type: string
    type: object
  handler.HttpStudent:
    properties:
      email:
        example: john@doe.com
        format: email
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      scopes:
        example: student
        type: string
    type: object
  http_error.HTTPBadRequestError:
    properties:
      error:
        example: error message
        type: string
      errors:
        items:
          $ref: '#/definitions/validator.FieldError'
        type: array
    type: object
  http_error.HTTPError:
    properties:
      error:
        example: error message
        type: string
    type: object
  httputil.PingInternalServerErr:
    properties:
      message:
        example: unexpected error
        type: string
    type: object
  httputil.PingOk:
    properties:
      message:
        example: pong
        type: string
    type: object
  validator.FieldError:
    properties:
      field:
        example: field_name
        type: string
      message:
        example: field_name is required
        type: string
    type: object
info:
  contact: {}
  termsOfService: github.com/jeanmolossi/vigilant-waddle/terms/
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/adapter.AuthCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HttpAccessToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_error.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http_error.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/http_error.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_error.HTTPError'
      summary: Login
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Login
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/handler.HttpAcceptedLogout'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - access_token: []
      summary: Logout
      tags:
      - auth
  /me:
    get:
      description: Get current student
      operationId: get-me
      parameters:
      - description: fields to return from the student
        in: query
        items:
          type: string
        name: fields
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HttpNewStudent'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/http_error.HTTPError'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/http_error.HTTPError'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/http_error.HTTPError'
      security:
      - access_token: []
      summary: Get current student
      tags:
      - auth
  /ping:
    get:
      consumes:
      - application/json
      description: A simple health check.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.PingOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
      summary: Ping the server.
      tags:
      - healthcheck
  /producer:
    post:
      description: Register a producer
      operationId: register-producer
      parameters:
      - description: Producer
        in: body
        name: producer
        required: true
        schema:
          $ref: '#/definitions/adapter.RegisterProducer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.HttpNewProducer'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/http_error.HTTPBadRequestError'
        "409":
          description: User with that email already exists
          schema:
            $ref: '#/definitions/http_error.HTTPError'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/http_error.HTTPError'
      summary: Register a producer
      tags:
      - producer
  /student:
    post:
      description: Register a student
      operationId: register-student
      parameters:
      - description: Student
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/adapter.RegisterStudent'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.HttpNewStudent'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/http_error.HTTPBadRequestError'
        "409":
          description: User with that email already exists
          schema:
            $ref: '#/definitions/http_error.HTTPError'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/http_error.HTTPError'
      summary: Register a student
      tags:
      - student
  /students:
    get:
      description: Get all students
      operationId: get-students
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items: {}
            type: array
      security:
      - access_token: []
      summary: Get all students
      tags:
      - student
securityDefinitions:
  access_token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
