definitions:
  adapter.RegisterStudent:
    properties:
      email:
        example: john@doe.com
        type: string
      password:
        example: "123456"
        maxLength: 64
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  handler.HttpNewStudent:
    properties:
      data:
        $ref: '#/definitions/handler.HttpStudent'
    type: object
  handler.HttpStudent:
    properties:
      email:
        example: john@doe.com
        format: email
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
    type: object
  http_error.HTTPBadRequestError:
    properties:
      error:
        example: error message
        type: string
      errors:
        items:
          $ref: '#/definitions/validator.FieldError'
        type: array
    type: object
  http_error.HTTPError:
    properties:
      error:
        example: error message
        type: string
    type: object
  httputil.PingInternalServerErr:
    properties:
      message:
        example: unexpected error
        type: string
    type: object
  httputil.PingOk:
    properties:
      message:
        example: pong
        type: string
    type: object
  validator.FieldError:
    properties:
      field:
        example: field_name
        type: string
      message:
        example: field_name is required
        type: string
    type: object
info:
  contact: {}
  termsOfService: github.com/jeanmolossi/vigilant-waddle/terms/
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: A simple health check.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.PingOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
      summary: Ping the server.
      tags:
      - healthcheck
  /student:
    post:
      description: Register a student
      operationId: register-student
      parameters:
      - description: Student
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/adapter.RegisterStudent'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.HttpNewStudent'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/http_error.HTTPBadRequestError'
        "409":
          description: User with that email already exists
          schema:
            $ref: '#/definitions/http_error.HTTPError'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/http_error.HTTPError'
      summary: Register a student
  /students:
    get:
      description: Get all students
      operationId: get-students
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items: {}
            type: array
      summary: Get all students
securityDefinitions:
  access_token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
